### PR TITLE
Fixes in riviera support which was pushed onto 1.3 version

### PR DESCRIPTION
**Pull request by danielmlynek**
This one was opened as not all changes from https://github.com/chipsalliance/Cores-SweRV-EL2/pull/11 was not properly merged into master 1.3

### CODE REVIEW

**Comment by agrobman** [comment]
Why do you change RTL?
RIVIERA variable in Makefile is not used - why to change?
Why to change what is deleted by make clean ? Don't create work directory where you run simulations ...

**Comment by danielmlynek** [comment]
> Why do you change RTL?
Initializing signal to default value at the begining  of process may lead to glitches an in this case it cause deadlock between proceses

> RIVIERA variable in  Makefile is not used - why to change?
That is true. There was a typo so Ijust have fix it. This variable can be removed or may be used to define name of riviera compilation/simulation program. Let me know if I should open PR to fix it.

> Why to change what is deleted by make clean ? Don't create work directory where you run simulations ...
"work" was dublicated so I've removed the 2nd its occurense from make clean list.

**Comment by agrobman** [comment]
Hi Daniel,

Did the original RTL code cause any simulation/synthesis problem? 

All our simulation/synthesis tools did not flag this. Furthermore, this coding style is recommended by Synopsis as less prone to infer unwanted latches in combo logic.

The code represents combinatorial logic which is by definition glitchy and there are other pieces of glitchy logic in the core.
I've never heard that combo logic in RTL cause any deadlocks ..   

Please, do not ask to change not essential or style related things.

**Comment by danielmlynek** [comment]
>Please, do not ask to change not essential or style related things.

Some simulators hangs on orginal code - that is why I've requested this change.

**Comment by aprnath** [comment]
@danielmlynek, it is perfectly OK to request changes. If they are reasonable and compatible with our toolsets, they will be considered for merging. We do run LEC on all requested RTL changes that do not modify the functionality or fix bugs. 

Thank you for your contributions.

**Pull request merged**
